login/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    #path('',include()),
    path('login/',views.login_request,name="login"),
    path('register/',views.register_student,name="register"),
    path('register-teacher/',views.register_teacher,name="register"),
    path('register-student/',views.register_student,name="register"),
    path('logout',views.signout,name="site-logout"),
    #path('googleauth',views.googleLogin,name="googleLogin")
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name = 'homepage'),
    path('contact/', views.contact, name = 'contact'),
]

majorProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('main.urls')),
    path('',include('login.urls')),
    #path('api/content/',include('content.api.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls')),
    path('content/', include('content.urls')),
    path('upload/', include('videoUpload.urls')),
    path('test/',include('quiz.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('proc/',include('proctoring.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/includes/header.html
{%load static%}

<head>    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!--<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">   
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">  -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">   -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.min.css' %}"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/templatemo-style.css' %}">
    <script src="{% static 'js/bootstrap.minjs' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- <script src="{% static 'js/owl.carousel.min.js' %}"></script> -->
    <script src="{% static 'js/smoothscroll.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>

    <base href = "http://127.0.0.1:8000/">

    <section class="preloader">
        <div class="spinner">
            
             <span class="spinner-rotate"></span>
             
        </div>
   </section>

    <section class="navbar custom-navbar fixed-top" role="navigation">
        <div class="container">
    
             <div class="navbar-header">
                  <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                       <span class="icon icon-bar"></span>
                       <span class="icon icon-bar"></span>
                       <span class="icon icon-bar"></span>
                  </button>
    
                  
                  <a href="#" class="navbar-brand">Learn</a>
             </div>

             <div class="collapse navbar-collapse">
                  <ul class="nav  navbar-nav navbar-nav-first">
                       <li><a href="home/" class="smoothScroll">Home</a></li>
                       <li><a href="teachers/" class="smoothScroll">Our Teachers</a></li>
                       <li><a href="content/" class="smoothScroll">Courses</a></li>
                       <li><a href="content/reviews/" class="smoothScroll">Reviews</a></li>
                       <li><a href="contact/" class="smoothScroll">Contact</a></li>
                       <li><a href="#about" class="smoothScroll">Your Cart</a></li>
                  </ul>
    
                  <ul class="nav navbar-nav navbar-right">
                       <li><a href="/login/"><i class="fa fa-user"></i> Login</a></li>
                  </ul>
             </div>
    
        </div>
    </section>

    {% block content%}
    {% endblock %}

    <footer id="footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 col-sm-6">
                    <div class="footer-info">
                            <div class="section-title">
                                <h2>Headquarter</h2>
                            </div>
                            <address>
                                <p>Kurukshetra Hostel<br>PUNJAB ENGINEERING COLLEGE<br>CHANDIGARH, 160012</p>
                            </address>

                            <ul class="social-icon">
                                <li><a href="#" class="fa fa-facebook-square" attr="facebook icon"></a></li>
                                <li><a href="#" class="fa fa-twitter"></a></li>
                                <li><a href="#" class="fa fa-instagram"></a></li>
                            </ul>

                            <div class="copyright-text"> 
                                <p>Copyright &copy; 2019 Learn.Inc</p>
                            </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6">
                    <div class="footer-info">
                            <div class="section-title">
                                <h2>Contact Info</h2>
                            </div>
                            <address>
                                <p>+91-132456789</p>
                                <p><a href="mailto:youremail.co">example@abcxyz.com</a></p>
                            </address>

                            <div class="footer_menu">
                                <h2>Quick Links</h2>
                                <ul>
                                    <li><a href="#">Career</a></li>
                                    <li><a href="#">Terms & Conditions</a></li>
                                    <li><a href="#">Refund Policy</a></li>
                                </ul>
                            </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-12">
                    <div class="footer-info newsletter-form">
                            <div class="section-title">
                                <h2>Newsletter Signup</h2>
                            </div>
                            <div>
                                <div class="form-group">
                                    <form action="#" method="get">
                                        <input type="email" class="form-control" placeholder="Enter your email" name="email" id="email" required="">
                                        <input type="submit" class="form-control" name="submit" id="form-submit" value="Send me">
                                    </form>
                                    <span><sup>*</sup> Please note - we do not spam your email.</span>
                                </div>
                            </div>
                    </div>
                </div>
                
            </div>
        </div>
    </footer>

</body>

templates/includes/header_new.html
<!doctype html>
<html lang="en" style="height: 100%;">
	<head>
		{%load static%}
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
		<!-- using bootstrap icons rather than font-awesome -->
      <!-- Bootstrap icon css -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
	</head>

	<body style="padding-top: 70px; min-height: 100%; display: flex; flex-direction: column; ">

	<base href = "https://team-17-major.herokuapp.com/">
	
	<!-- *navbar -->
	<div id="navbar"> 
		<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarTogglerDemo01">
					<a href="#" class="navbar-brand">
                  <!-- *! add logo image -->
						<img src="{%static 'images/logo.jpeg'%}" style="height: 35px; width: 80px; border-radius: 20px;" alt="logo"> 
					</a>
					<ul class="navbar-nav mr-auto mt-0 mt-lg-0">
						<li class="nav-item ">
							<a class="nav-link" href="#">Home</a>
						</li>
						<li class="nav-item ">
							<a class="nav-link" href="content/">Courses</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="teachers/">Instructors</a>
						</li>
						{% if log %}
							<li class="nav-item">
								<a class="nav-link " href="dashboard/">Dashboard</a>
							</li>
						{%endif%}
						<li class="nav-item">
							<a class="nav-link " href="contact/">Contact us</a>
						</li>
					</ul>

					{% if not log %}
					<ul class="navbar-nav mt-0 mt-lg-0">
						<li class="nav-item">
							<a class="nav-link" href="login/">Login/Sign-in</a>
						</li>
					</ul>
					{%endif%}

					{% if log %}
					<ul class="navbar-nav mt-0 mt-lg-0">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'login:site-logout' %}">{{u}} - Logout</a>
						</li>
					</ul>
					{%endif%}
			</div>
		</nav>
	</div>

		<!-- *! add the other templates in between navbar and footer  -->

	{% block content%}


	{% endblock %}


	<!-- *Footer -->
	<footer class="text-center text-lg-start text-white" style="background-color: #1c2331; margin-top: auto; width: 100%;">

		<!-- Section: Social media -->
		<section class="d-flex justify-content-between p-2" style="background-color: #6351ce">
			<!-- Left -->
			<div class="me-5">
					<span>Get connected with us on social networks:</span>
			</div>
			<!-- Right -->
			<div>
					<a href="" class="text-white me-4"><i class="bi bi-facebook mr-4"></i></a>
					<a href="" class="text-white me-4"><i class="bi bi-twitter mr-4"></i></a>
					<a href="" class="text-white me-4"><i class="bi bi-google mr-4"></i></a>
					<a href="" class="text-white me-4"><i class="bi bi-instagram mr-4"></i></a>
					<a href="" class="text-white me-4"><i class="bi bi-linkedin mr-4"></i></a>
					<a href="" class="text-white me-4"><i class="bi bi-github mr-4"></i></a>
			</div>
		</section>

		<!-- Section: Links  -->
		<section class="">
			<div class="container text-center text-md-start mt-3">
					<!-- Grid row -->
					<div class="row mt-2">
						<!-- Grid column -->
						<div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-2">
							<!-- Content -->
							<h6 class="text-uppercase fw-bold">GLP</h6>
							<hr class="mb-2 mt-0 d-inline-block mx-auto" style="width: 30px; background-color: #7c4dff; height: 2px" />
							<p>
									We are a group of people that want to see the that quality education 
									does not cost you a fortune and is available everywhere.
							</p>
						</div>

						<!-- Grid column -->
						<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-2">
							<!-- Links -->
							<h6 class="text-uppercase fw-bold">Products</h6>
							<hr class="mb-2 mt-0 d-inline-block mx-auto" style="width: 80px; background-color: #7c4dff; height: 2px" />
							<p> <a href="#!" class="text-white">Technology Courses</a> </p>
							<p> <a href="#!" class="text-white">Most Popular</a> </p> 
							<p> <a href="#!" class="text-white">Highest Rated</a> </p>
							<p> <a href="#!" class="text-white"></a> </p>
						</div>

						<!-- Grid column -->
						<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-2">
							<!-- Links -->
							<h6 class="text-uppercase fw-bold">Useful links</h6>
							<hr class="mb-2 mt-0 d-inline-block mx-auto" style="width: 95px; background-color: #7c4dff; height: 2px" />
							<p> <a href="#!" class="text-white">Your Account</a> </p>
							<p> <a href="#!" class="text-white">Become an Instructor</a> </p>
							<p> <a href="#!" class="text-white"></a> </p>
							<p> <a href="#!" class="text-white">Help</a> </p>
						</div>

						<!-- Grid column -->
						<div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-2">
							<!-- Links -->
							<h6 class="text-uppercase fw-bold">Contact</h6>
							<hr class="mb-2 mt-0 d-inline-block mx-auto" style="width: 60px; background-color: #7c4dff; height: 2px" />
							<p><i class="bi bi-house-fill mr-2"></i> Chandigarh, CHD 160036, IND</p>
							<p><i class="bi bi-envelope-fill mr-2"></i> info@example.com</p>
							<p><i class="bi bi-telephone-fill mr-2"></i> + 01122334455</p>
						</div>
					</div>
			</div>
		</section>

		<!-- Copyright -->
		<div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.2)">
			© 2020-21 Copyright: <a class="text-white" href="#" >GLP Pvt. Ltd.</a>
		</div>

	</footer>
	<!-- Footer -->

	
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
	</body>
</html>