login/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    #path('',include()),
    path('login/',views.login_request,name="login"),
    path('register/',views.register_student,name="register"),
    path('register-teacher/',views.register_teacher,name="register"),
    path('register-student/',views.register_student,name="register"),
    path('logout',views.signout,name="site-logout"),
    #path('googleauth',views.googleLogin,name="googleLogin")
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name = 'homepage'),
    path('contact/', views.contact, name = 'contact'),
]

proctoring/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'proctoring'

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('video_feed',views.video_feed,name='video_feed')
]

quiz/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'test'

urlpatterns = [
    #path('',include()),
    path('<single_slug>',views.dispTest,name="test"),
    path('score/<single_slug>/',views.result,name="score"),
    #path('googleauth',views.googleLogin,name="googleLogin")
]

teachers/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'teachers'

urlpatterns = [
    path('', views.teacherView, name='teachers'),
]

login/models.py
from django.db import models

# Create your models here.

quiz/models.py
from django.db import models
from content.models import course

# Create your models here.
# make a quiz model that has the tutorial for which this quiz is being made and also assign a quiz 
# no that helps to find which quiz is being referred to 
# then make a question model which has the tutorial and quiz number and has the question and the options for 
# that question


class quiz(models.Model):
    course_name = models.ForeignKey(course,default=1,on_delete=models.SET_DEFAULT)
    quiz_name = models.CharField(max_length=200)
    quiz_slug = models.CharField(max_length=300,blank=True)
    def __str__(self):
        return self.quiz_name

class question(models.Model):
    course_name = models.ForeignKey(course,default=1,on_delete=models.SET_DEFAULT)
    quiz_name = models.ForeignKey(quiz,default=1,on_delete=models.SET_DEFAULT)
    quiz_question = models.TextField()
    option_one = models.TextField()
    option_two = models.TextField()
    option_three = models.TextField()
    option_four = models.TextField()
    picture = models.ImageField(blank = True,null=True)
    answer = models.TextField()

teachers/models.py
from django.db import models

# Create your models here.

class teacherData(models.Model):
    teacher_name = models.CharField(max_length=200)
    Education = models.CharField(max_length=400)
    facebook_id = models.SlugField(max_length=400)
    instagram_id = models.SlugField(max_length=400)
    email_id = models.SlugField(max_length=400)
    tag_line = models.CharField(max_length=400)
    teacher_image = models.ImageField(blank=True)
    def __str__(self):
        return self.teacher_name

videoUpload/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout,authenticate
from .loginForm import LoginForm
from .registerForm import RegisterForm
from django.contrib import messages
from dashboard.models import student_details
from django.contrib.auth.models import User
from content.models import course_reviews
from django.shortcuts import HttpResponseRedirect
# Create your views here.



def login_request(request):
    loggen_in = False
    if request.user.is_authenticated:
        loggen_in = True    
    if request.method == "POST":
        form = LoginForm(request,data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username,password = password)
            if user is not None:
                login(request,user,backend='django.contrib.auth.backends.ModelBackend')
                messages.info(request,f"You are now logged in as {username}")
                return redirect('/dashboard/')
            else:
                messages.error(request,"Invalid Username or Password")
        else:
            messages.error(request,"Invalid Username or Password")
    form = LoginForm
    return render(request,"login_form_new.html",context={"form":form,'log':loggen_in, 'u':request.user})

def register_student(request):
    loggen_in = False
    if request.user.is_authenticated:
        loggen_in = True       
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"New Account Created: {username}")
            login(request,user,backend='django.contrib.auth.backends.ModelBackend')
            #user = User.objects.get(username=username)
            temp = student_details(username=user)
            temp.save()
            print(temp.username)
            return redirect('/dashboard/')
        else:
            for msg in form.error_messages:
                messages.error(request,f"{msg}: form.error_messages[msg]")
    form = RegisterForm
    return render(request,"signup_form_new.html",context={"form":form,'log':loggen_in, 'u':request.user})

def register_teacher(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"New Account Created: {username}")
            login(request,user,backend='django.contrib.auth.backends.ModelBackend')
            return redirect('dashboard.view_dashboard')
        else:
            for msg in form.error_messages:
                messages.error(request,f"{msg}: form.error_messages[msg]")
    form = RegisterForm
    return render(request,"register-teacher.html",context={"form":form})

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"New Account Created: {username}")
            login(request,user,backend='django.contrib.auth.backends.ModelBackend')
            return redirect('dashboard.view_dashboard')
        else:
            for msg in form.error_messages:
                messages.error(request,f"{msg}: form.error_messages[msg]")
    form = RegisterForm

    return render(request,"register.html",context={"form":form})

#def register_teacher(request):
 #   if request.method == "POST":
 #       form = RegisterForm(request.POST)
 #       if form.is_valid():
 #           user = form.save()
 #           user.group = 
 #           username = form.cleaned_data.get('username')
 #           messages.success(request,f"New Account Created: {username}")
 #           login(request,user,backend='django.contrib.auth.backends.ModelBackend')
 #           return redirect('main:homepage')
 #       else:
 #           for msg in form.error_messages:
 #               messages.error(request,f"{msg}: form.error_messages[msg]")
 #   form = RegisterForm
 #   return render(request,"register.html",context={"form":form})

def googleLogin(request):
    return render(request, "googleLogin.html")

def signout(request):
    logout(request)
    return HttpResponseRedirect('/login/')

quiz/views.py
from django.shortcuts import render
from .models import quiz,question
from content.models import course
from dashboard.models import quiz_scores

# Create your views here.

def dispTest(request,single_slug):
    #if request.method == "POST":
    #    print('true')
    #if request.method == "POST":
    loggen_in = False
    if request.user.is_authenticated:
        loggen_in = True
    for q in quiz.objects.all():
        if q.quiz_slug == single_slug:
            q_obj = q
    title = q_obj.quiz_name
    slug = q_obj.quiz_slug
    questions = []
    for q in question.objects.all():
        if q.course_name == q_obj.course_name:
            #print('true')
            if q.quiz_name == q_obj:
                questions.append(q)
    #print(questions)
    #print(title)
    return render(request,'quiz_new.html',{'question':questions,'title':title,'single_slug':slug,'log':loggen_in, 'u':request.user})

def result(request,single_slug):
    #print(request.POST)
    #print(request.POST[str(1)])
    loggen_in = False
    if request.user.is_authenticated:
        loggen_in = True
    for q in quiz.objects.all():
        if q.quiz_slug == single_slug:
            q_obj = q
    for c in course.objects.all():
        if q_obj.course_name == c:
            print('c trye')
            c_obj = c
    current_user = request.user
    total = 0
    val = 1
    for q in question.objects.all():
        try:
            if request.POST[str(val)] == q.answer:
                total+=1
            val+=1
        except:
            pass
    temp = quiz_scores(username = current_user, course_name = c_obj, quiz_name = q_obj,score = total)
    temp.save()
    return render(request,'score.html',{'total':total,'log':loggen_in, 'u':request.user})

teachers/views.py
from django.shortcuts import render
from content.models import instructor,course

# Create your views here.

def teacherView(request):
    loggen_in = False
    if request.user.is_authenticated:
        loggen_in = True
    teacher_dict = {}
    for i in instructor.objects.all():
        new_list = []
        for c in course.objects.all():
            if c.instructor_name == i.instructor_name:
                new_list.append(c.course_name)
        teacher_dict[i] = new_list
    return render(request,'instructors_new.html',{'inst':teacher_dict.items(),'log':loggen_in, 'u':request.user})

videoUpload/views.py
from content.models import course
from django.contrib.auth.models import User
from django.shortcuts import render

def trial(request): 
    return render(request,'timepass.html',context={'tuts':course.objects.all(),'user':User.objects.all()})

templates/course_details.html
{% extends "includes/header_new.html" %}

{%block content%}
	{%load static%}


    <div class="container-fluid my-2">
		<div class="row" style="justify-content: center;">
			<div class="col-md-7" >
				<div class="row" style="justify-content: center;">
					<h2 class="text-muted">{{course.course_name}}</h2>
				</div>
				<div class="row" style="justify-content: center;">
					<!-- Write a big enough paragraph for course description -->
					<p>{{course.course_info}}
					</p>
				</div>
				<div class="row" style="justify-content: center;">
					<h4 class="text-muted"> <small><strong>Medium of Instruction:</strong> </small> &nbsp; </h4>
					<h4> <small>English </small></h4>
				</div>
				<div class="row" style="justify-content: center;">
					<h4 class="text-muted"> <small><strong>Time for completion (Approx): </strong></small>  &nbsp; </h4>
					<h4> <small>{{course.completion_time}} </small></h4>
				</div>				
			</div>
			<div class="col-md-4 my-3">
				<div class="row my-3" style="justify-content: center;">
					<i class="bi bi-globe"></i>
					<p class="font-weight-bold" style="display: inline;"> &nbsp;100% Online </p>
				</div>
				<div class="row my-3" style="justify-content: center;">
					<i class="bi bi-file-text"></i>
					<p class="font-weight-bold" style="display: inline;">&nbsp; Certification of completion</p>
				</div>
				<div class="row my-3" style="justify-content: center;">
					<i class="bi bi-chat-left-dots"></i>
					<p class="font-weight-bold" style="display: inline;">&nbsp; Medium Of Instruction: </p>
					<h6 class="text-muted" style="display: inline;">&nbsp; English</h6>
				</div>
				<div class="row my-3" style="justify-content: center;">
					<i class="bi bi-calendar-check"></i>
					<p class="font-weight-bold" style="display: inline;">&nbsp; Flexible Schedule </p>
				</div>
			</div>
		</div>
		<div class="row my-2" style="justify-content: center;">
            <button type="submit" onclick="location.href = 'content/enroll/{{course.course_slug}}';" id="myButton" class="btn btn-primary" >Enroll</button>
		</div>
		<div style="position: relative; display: inline-block; margin-left: 3px; margin-right: 3px; width: 100%; border-bottom: 1px solid #7A7A7A;"></div>
	</div>

	<!-- *! card-2 Instructor details -->
	<div class="container my-5">
		<div class="card">
			<div class="row" style="justify-content: center;">
				<div class="col-md-3 col-sm-12" style="margin: auto; justify-content: center;">
					<img src="{{ins.instructor_img.url}}" style="height: 300px; width: 250px; margin-left: 75px;" alt="Instructor-picture">
				</div>
				<div class="col-md-9 col-sm-12 " style="text-align: center;">
					<h3 class="mt-3 mb-2">Instructor</h3>
					<hr class="bg-primary mt-0 w-25">
					<div class="row my-3">
						<div class="col-sm-6">
							<p class="font-weight-bold">Name:</p>
								<h6 class=" text-muted">{{ins.instructor_name}}</h6>
						</div>
						<div class="col-sm-6">
							<p class="font-weight-bold">Email:</p>
								<h6 class="text-muted">{{ins.instructor_email}}</h6>
						</div>
					</div>
					<hr class="bg-primary mx-5">
					<div class="row my-3">
						<div class="col-sm-6">
							<p class="font-weight-bold">College:</p>
								<h6 class=" text-muted">{{ins.instructor_college}}</h6>
						</div>
						<div class="col-sm-6">
							<p class="font-weight-bold">Branch/Major:</p>
								<h6 class="text-muted">{{ins.instructor_specialization}}</h6>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


{%endblock%}

templates/courses.html
{% extends "includes/header.html" %}

{%block content%}
    <!-- Courses -->
    {%load static%}
    <section id="courses">
        <div class="container">
             <div class="row">
                  <div class="col-md-12 col-sm-12">
                       <div class="section-title">
                            <h2>Popular Courses <small>Upgrade your skills with newest courses</small></h2>
                       </div>
                       <div class="owl-carousel owl-theme owl-courses">
                              {% for course in var%}
                                   <div class="col-md-4 col-sm-4">
                                        <div class="item">
                                             <div class="courses-thumb">
                                                  <div class="courses-top">
                                                       <div class="courses-image">
                                                            <!--<img src="images/courses-image1.jpg" class="img-responsive" alt="">-->
                                                            <img src="{{course.course_thumbnail.url}}" class="img-responsive" alt="">
                                                       </div>
                                                       <div class="courses-date">
                                                            <span><i class="fa fa-calendar"></i> 12 / 9 / 2020</span>
                                                            <span><i class="fa fa-clock-o"></i> 3.5 Hours</span>
                                                       </div>
                                                  </div>
     
                                                  <div class="courses-detail">
                                                       <h3><a href="content/{{course.course_slug}}"> {{course.course_name}} </a></h3>
                                                       <p>{{course.course_info}}</p>
                                                  </div>
     
                                                  <div class="courses-info">
                                                       <div class="courses-author">
                                                            <!--<img src="images/author-image1.jpg" class="img-responsive" alt="">-->
                                                            
                                                            <img src="{{var.course.instructor_img.url}}" class="img-responsive" alt="">
                                                            <span>{{course.instructor_name}}</span>
                                                       </div>
                                                       <div class="courses-price">
                                                            <a href="content/enroll/{{course.course_slug}}"><span>Enroll</span></a>
                                                       </div>
                                                  </div>
                                             </div>
                                        </div>
                                   </div>
                              {% endfor %}
                       </div>
                    </div>
             </div>
        </div>
   </section>
{%endblock%}

templates/courses_new.html
{% extends "includes/header_new.html" %}

{%block content%}
	{%load static%}
	<!-- *! card for courses -->
	{% for course in var%}
	<div class="container-fluid my-2" >
		<div class="card" style="border-style: none;">
			<div class="row">
				<div class="offset-md-2 col-md-4">
					<!-- image -->
					<img src="{{course.course_thumbnail.url}}" alt="course image" style="height: 200px; width: 100%; justify-content: center;">
				</div>
				<div class="col-md-4" style="justify-content: center;">
					<div class="row" style="justify-content: center;">
						<!-- Name of course -->
						<h4 class="text-muted">{{course.course_name}}</h4>
					</div>
					<div class="row" style="justify-content: center;">
						<!-- Instructor -->
						<h4 class="text-muted"><small><strong>Instructor: </strong></small> &nbsp; </h4>
						<h4> <small> {{course.instructor_name}} </small></h4>
					</div>
					<div class="row" style="justify-content: center;">
						<!-- Medium of instruction -->
						<h4 class="text-muted"> <small><strong>Medium of Instruction:</strong> </small> &nbsp; </h4>
						<h4> <small>English </small></h4>
					</div>
					<div class="row" style="justify-content: center;">
						<!-- Medium of instruction -->
						<h4 class="text-muted"> <small><strong>Time for completion (Approx): </strong></small>  &nbsp; </h4>
						<h4> <small>{{course.completion_time}} </small></h4>
					</div>
					<div class="row my-1" style="justify-content: center;">
						<!-- button -->
						<button type="submit" onclick="location.href = 'content/details/{{course.course_slug}}';" id="myButton" class="btn btn-primary" >Enroll</button>
					</div>
				</div>
			</div>
		</div>
		<div style="position: relative; display: inline-block; margin-left: 3px; margin-right: 3px; width: 100%; border-bottom: 1px solid #7A7A7A;"></div>
	</div>
	{%endfor%}
{%endblock%}

templates/home.html
{% extends "includes/header.html" %}

{%block content%}
{%load static%}

    <section id="home">
        <div class="row">
            <div class="owl-carousel owl-theme home-slider">
                <div class="item item-first">
                    <div class="caption">
                        <div class="container">
                            <div class="col-md-6 col-sm-12">
                                <h1>Distance Learning Education Center</h1>
                                <h3>Our online courses are designed to fit in your industry supporting all-round with latest technologies.</h3>
                                <a href="#feature" class="section-btn btn btn-default smoothScroll">Discover more</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item item-second">
                    <div class="caption">
                        <div class="container">
                            <div class="col-md-6 col-sm-12">
                                <h1>Start your journey with our practical courses</h1>
                                <h3>Our online courses are built in partnership with technology leaders and are designed to meet industry demands.</h3>
                                <a href="#courses" class="section-btn btn btn-default smoothScroll">Take a course</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item item-third">
                    <div class="caption">
                        <div class="container">
                            <div class="col-md-6 col-sm-12">
                                <h1>Efficient Learning Methods</h1>
                                <h3>Nam eget sapien vel nibh euismod vulputate in vel nibh. Quisque eu ex eu urna venenatis sollicitudin ut at libero. Visit <a rel="nofollow" href="https://www.facebook.com/templatemo">templatemo</a> page.</h3>
                                <a href="#contact" class="section-btn btn btn-default smoothScroll">Let's chat</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- FEATURE -->
    <section id="feature">
        <div class="container">
            <div class="row">

                <div class="col-md-4 col-sm-4">
                    <div class="feature-thumb">
                            <span>01</span>
                            <h3>Trending Courses</h3>
                            <p>Known is free education HTML Bootstrap Template. You can modify in any way and use this for your website.</p>
                    </div>
                </div>

                <div class="col-md-4 col-sm-4">
                    <div class="feature-thumb">
                            <span>02</span>
                            <h3>Books & Library</h3>
                            <p>You are allowed to use Known HTML Template for your commercial or non-commercial websites.</p>
                    </div>
                </div>

                <div class="col-md-4 col-sm-4">
                    <div class="feature-thumb">
                            <span>03</span>
                            <h3>Certified Teachers</h3>
                            <p>Please spread a word about us. Template redistribution is NOT allowed on any download website.</p>
                    </div>
                </div>

            </div>
        </div>
    </section>
{%endblock%}

templates/home_new_new.html
{% extends "includes/header_new.html" %}

{%block content%}


{%load static%}


<div class="row" style="position: relative; margin: 0px 0; padding: 0px 0;">
    <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators" style="bottom: -35px;">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active" style="background-color: black;"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1" style="background-color: black;"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2" style="background-color: black;"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div style="width: 150px; height: 150px; margin: auto; overflow: hidden; border: 2px solid #fff; border-radius: 50%;">
                    <img src= "{{start.reviewer_img.url}}" alt="{{start.slide}}" style="width: 100%;">
                    </div>
                    <div class="carousel-caption" style="position: static; padding-top: 5px; padding-bottom: 15px;">
                    <h3 style="color: black;">{{start.reviewer_name}}</h3>
                    <h7 style="color: rgb(0, 4, 243);">{{start.reviewer_about}}</h7>
                    <p style="color: black;">{{start.review_para}}</p>
                    </div>
                </div>
                {% for r in rev%}
                    <div class="carousel-item">
                        <div style="width: 150px; height: 150px; margin: auto; overflow: hidden; border: 2px solid #fff; border-radius: 50%;">
                        <img src= "{{r.reviewer_img.url}}" alt="{{r.slide}}" style="width: 100%;">
                        </div>
                        <div class="carousel-caption" style="position: static; padding-top: 5px; padding-bottom: 15px;">
                        <h3 style="color: black;">{{r.reviewer_name}}</h3>
                        <h7 style="color: rgb(0, 4, 243);">{{r.reviewer_about}}</h7>
                        <p style="color: black;">{{r.review_para}}</p>
                        </div>
                    </div>
                {% endfor %}
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" > 
                <span class="carousel-control-prev-icon" aria-hidden="true" style="background-color: black;"></span>
                <span class="sr-only" >Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true" style="background-color: black;"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

 <!-- * Learn more about the courses offered section -->
 <div class="container mx-auto mt-1" style="padding: 0px; ">
    <div class="row mx-auto" style="padding-top: 20px; padding-bottom: 20px; width: 90%;">
       <div class=" col-md-6">
          <div class="row my-3">
             <h3 class="mx-auto" style="color: rgb(0, 0, 0);">Learn What you Want</h3>
          </div>
          <div class="row my-5">
             <h4 class="mx-auto" style="color: rgb(0, 0, 0);">Take the Courses that Matter</h4>
          </div>
          <div class="row my-3">
             <!-- *! would have redirect onclick to signup form -->
             <button type="submit" onclick="location.href = 'content/';" id="myButton" class="btn btn-primary mx-auto" >Learn More</button>
          </div>
       </div>
       <div class="col-md-6 ">
          <img src="{%static 'images/learn-what-you-like.jpg'%}" alt="image" style="width: 90%; padding-right: 10px; border-radius: 5%;">
       </div>
    </div>
 </div>

 <!-- * the join for free section -->
 <div class="container mx-auto my-1" style="padding: 0px; margin: 0px;">
    <div class="row my-6 mx-auto" style="width: 90%; padding-top: 20px; padding-bottom: 20px;">
       <div class=" col-md-6">
          <img src="{%static 'images/stand-out-from-the-rest.jpg'%}" alt="" style="width: 90%; margin-left: auto; margin-right: auto; border-radius: 5%;">
       </div>
       <div class="col-md-6">
          <div class="row my-3">
             <h3 class="mx-auto" style="color: rgb(0, 0, 0);">Stand out from the rest</h3>
          </div>
          <div class="row my-5">
             <h4 class="mx-auto" style="color: rgb(0, 0, 0);">Take the next step towards your professional career</h4>
          </div>
          <div class="row">
             <!-- *! would have redirect onclick to signup form -->
             <button type="submit" onclick="location.href = 'register-student/';" id="myButton" class="btn btn-primary mx-auto" >Join For Free</button>
          </div>
       </div>
    </div>
 </div>

 {%endblock%}

templates/login.html
{% extends "includes/header.html" %}

{% load socialaccount%}
{% providers_media_js %}

{% block content %}
     <!-- ABOUT -->
     <section id="about">
        <div class="container">
             <div class="row">

                  <div class="col-md-6 col-sm-12">
                       <div class="about-info">
                            <h2>Start your journey to a better life with online practical courses</h2>

                            <figure>
                                 <span><i class="fa fa-users"></i></span>
                                 <figcaption>
                                      <h3>Professional Trainers</h3>
                                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint ipsa voluptatibus.</p>
                                 </figcaption>
                            </figure>

                            <figure>
                                 <span><i class="fa fa-certificate"></i></span>
                                 <figcaption>
                                      <h3>International Certifications</h3>
                                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint ipsa voluptatibus.</p>
                                 </figcaption>
                            </figure>

                            <figure>
                                 <span><i class="fa fa-bar-chart-o"></i></span>
                                 <figcaption>
                                      <h3>Free for 3 months</h3>
                                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint ipsa voluptatibus.</p>
                                 </figcaption>
                            </figure>
                       </div>
                  </div>

                  <div class="col-md-offset-1 col-md-4 col-sm-12">
                       <div class="entry-form">
                              <form method="POST">
                                   <h2>Login</h2>
                                   {%csrf_token%}
                                   {{form.as_p}}
                                   <button class="submit-btn form-control" id="form-submit">Get started</button>
                              </form>
                            <!--<form action="#" method="post">
                                 <h2>Signup today</h2>
                                 
                                 <input type="text" name="full name" class="form-control" placeholder="Full name" required="">

                                 <input type="email" name="email" class="form-control" placeholder="Your email address" required="">

                                 <input type="password" name="password" class="form-control" placeholder="Your password" required="">

                                 <button class="submit-btn form-control" id="form-submit">Get started</button>
                            </form>-->
                       </div>
                  </div>

             </div>
        </div>
   </section>
{% endblock %}

templates/timepass.html
<h1>
    Video Stream
</h1>
  
<img src="{% url 'proctoring:video_feed' %}">